# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-07 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180331_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='updown',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='updown',
            name='article',
        ),
        migrations.RemoveField(
            model_name='updown',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='down',
        ),
        migrations.RemoveField(
            model_name='article',
            name='up',
        ),
        migrations.DeleteModel(
            name='UpDown',
        ),
    ]
